# DOC_LINK: DOC-CONFIG-DIR-MANIFEST-CONTEXT-GLOSSARY-1003
classification: natural
dir_id: DIR-ALL_AI-CONTEXT-GLOSSARY-35b25cf4
doc_id: DOC-CONFIG-DIR-MANIFEST-CONTEXT-GLOSSARY-1003
files:
  documentation:
  - README.md
  metadata:
  - DIR_MANIFEST.yaml
  - .dir_id
  registries:
  - DOC-REGISTRY-TERM-ID-001__GLOSSARY_REGISTRY.yaml
meta: {}
ownership:
  created: '2026-01-04T01:30:14.047701Z'
  owner: Glossary Team
  status: active
purpose: Registry for Glossary Term Identifier (term_id)
version: 1.0.0
